# Generated by Django 3.0 on 2019-12-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191216_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='OTP',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='attempts',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='time_generate_otp',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
