# Generated by Django 2.2.7 on 2019-12-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_employee_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='disliked',
            field=models.CharField(default='', max_length=255),
        ),
    ]
