# Generated by Django 3.0 on 2019-12-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191219_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField()),
                ('OTP', models.IntegerField(null=True)),
                ('attempts', models.IntegerField(default=5)),
                ('time_generate_otp', models.TimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='OTP',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='time_generate_otp',
        ),
        migrations.AddField(
            model_name='employee',
            name='application_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
