# Generated by Django 3.0 on 2019-12-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20191219_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='time_generate_otp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
