# Generated by Django 3.0 on 2019-12-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20191220_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_verify',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
