# Generated by Django 3.0 on 2019-12-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_otp_is_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='is_verify',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
