# Generated by Django 3.0 on 2019-12-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20191220_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tags',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
