# Generated by Django 3.0 on 2019-12-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='channel_logo')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('followers', models.IntegerField()),
                ('total_views', models.IntegerField()),
                ('courses', models.CharField(max_length=50)),
                ('playlist', models.CharField(max_length=50)),
            ],
        ),
    ]
