# Generated by Django 3.0 on 2019-12-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20191223_1316'),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='channel',
            new_name='channel_model',
        ),
    ]
