# Generated by Django 2.2.7 on 2019-12-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_class',
            name='id',
        ),
        migrations.AlterField(
            model_name='video_class',
            name='channel_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video_class',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video_class',
            name='is_downloadable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video_class',
            name='is_sharable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video_class',
            name='length_of_video',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video_class',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video_class',
            name='playlist',
            field=models.CharField(default='video', max_length=100),
        ),
        migrations.AlterField(
            model_name='video_class',
            name='video',
            field=models.FileField(upload_to='video'),
        ),
    ]
