# Generated by Django 3.0 on 2019-12-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='video_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videous')),
                ('length_of_video', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('thumb_image', models.ImageField(upload_to='thumb_image')),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('playlist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('is_downloadable', models.BooleanField()),
                ('is_sharable', models.BooleanField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel_model')),
            ],
        ),
        migrations.DeleteModel(
            name='video',
        ),
    ]
