# Generated by Django 2.2.7 on 2019-12-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20191226_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_class',
            name='channel_id',
        ),
        migrations.AddField(
            model_name='video_class',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
