# Generated by Django 3.0.1 on 2020-01-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_class_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_class',
            name='tags',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
