# Generated by Django 3.0.1 on 2020-01-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_video_class_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_class',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
